// GENERATED by tools/gen-wasi-stubs.py — see that script for why.
#include <wasi/api.h>

__wasi_errno_t __wasi_args_get(uint8_t * * argv, uint8_t * argv_buf) {
    (void)argv;
    (void)argv_buf;
    return __WASI_ERRNO_NOTSUP;
}

__wasi_errno_t __wasi_args_sizes_get(__wasi_size_t *retptr0, __wasi_size_t *retptr1) {
    (void)retptr0;
    (void)retptr1;
    return __WASI_ERRNO_NOTSUP;
}

__wasi_errno_t __wasi_clock_res_get(__wasi_clockid_t id, __wasi_timestamp_t *retptr0) {
    (void)id;
    (void)retptr0;
    return __WASI_ERRNO_NOTSUP;
}

__wasi_errno_t __wasi_clock_time_get(__wasi_clockid_t id, __wasi_timestamp_t precision, __wasi_timestamp_t *retptr0) {
    (void)id;
    (void)precision;
    (void)retptr0;
    return __WASI_ERRNO_NOTSUP;
}

__wasi_errno_t __wasi_fd_advise(__wasi_fd_t fd, __wasi_filesize_t offset, __wasi_filesize_t len, __wasi_advice_t advice) {
    (void)fd;
    (void)offset;
    (void)len;
    (void)advice;
    return __WASI_ERRNO_NOTSUP;
}

__wasi_errno_t __wasi_fd_allocate(__wasi_fd_t fd, __wasi_filesize_t offset, __wasi_filesize_t len) {
    (void)fd;
    (void)offset;
    (void)len;
    return __WASI_ERRNO_NOTSUP;
}

__wasi_errno_t __wasi_fd_close(__wasi_fd_t fd) {
    (void)fd;
    return __WASI_ERRNO_NOTSUP;
}

__wasi_errno_t __wasi_fd_datasync(__wasi_fd_t fd) {
    (void)fd;
    return __WASI_ERRNO_NOTSUP;
}

__wasi_errno_t __wasi_fd_fdstat_get(__wasi_fd_t fd, __wasi_fdstat_t *retptr0) {
    (void)fd;
    (void)retptr0;
    return __WASI_ERRNO_NOTSUP;
}

__wasi_errno_t __wasi_fd_fdstat_set_flags(__wasi_fd_t fd, __wasi_fdflags_t flags) {
    (void)fd;
    (void)flags;
    return __WASI_ERRNO_NOTSUP;
}

__wasi_errno_t __wasi_fd_fdstat_set_rights(__wasi_fd_t fd, __wasi_rights_t fs_rights_base, __wasi_rights_t fs_rights_inheriting) {
    (void)fd;
    (void)fs_rights_base;
    (void)fs_rights_inheriting;
    return __WASI_ERRNO_NOTSUP;
}

__wasi_errno_t __wasi_fd_filestat_get(__wasi_fd_t fd, __wasi_filestat_t *retptr0) {
    (void)fd;
    (void)retptr0;
    return __WASI_ERRNO_NOTSUP;
}

__wasi_errno_t __wasi_fd_filestat_set_size(__wasi_fd_t fd, __wasi_filesize_t size) {
    (void)fd;
    (void)size;
    return __WASI_ERRNO_NOTSUP;
}

__wasi_errno_t __wasi_fd_filestat_set_times(__wasi_fd_t fd, __wasi_timestamp_t atim, __wasi_timestamp_t mtim, __wasi_fstflags_t fst_flags) {
    (void)fd;
    (void)atim;
    (void)mtim;
    (void)fst_flags;
    return __WASI_ERRNO_NOTSUP;
}

__wasi_errno_t __wasi_fd_pread(__wasi_fd_t fd, const __wasi_iovec_t *iovs, size_t iovs_len, __wasi_filesize_t offset, __wasi_size_t *retptr0) {
    (void)fd;
    (void)iovs;
    (void)iovs_len;
    (void)offset;
    (void)retptr0;
    return __WASI_ERRNO_NOTSUP;
}

__wasi_errno_t __wasi_fd_prestat_dir_name(__wasi_fd_t fd, uint8_t * path, __wasi_size_t path_len) {
    (void)fd;
    (void)path;
    (void)path_len;
    return __WASI_ERRNO_NOTSUP;
}

__wasi_errno_t __wasi_fd_pwrite(__wasi_fd_t fd, const __wasi_ciovec_t *iovs, size_t iovs_len, __wasi_filesize_t offset, __wasi_size_t *retptr0) {
    (void)fd;
    (void)iovs;
    (void)iovs_len;
    (void)offset;
    (void)retptr0;
    return __WASI_ERRNO_NOTSUP;
}

__wasi_errno_t __wasi_fd_read(__wasi_fd_t fd, const __wasi_iovec_t *iovs, size_t iovs_len, __wasi_size_t *retptr0) {
    (void)fd;
    (void)iovs;
    (void)iovs_len;
    (void)retptr0;
    return __WASI_ERRNO_NOTSUP;
}

__wasi_errno_t __wasi_fd_readdir(__wasi_fd_t fd, uint8_t * buf, __wasi_size_t buf_len, __wasi_dircookie_t cookie, __wasi_size_t *retptr0) {
    (void)fd;
    (void)buf;
    (void)buf_len;
    (void)cookie;
    (void)retptr0;
    return __WASI_ERRNO_NOTSUP;
}

__wasi_errno_t __wasi_fd_renumber(__wasi_fd_t fd, __wasi_fd_t to) {
    (void)fd;
    (void)to;
    return __WASI_ERRNO_NOTSUP;
}

__wasi_errno_t __wasi_fd_seek(__wasi_fd_t fd, __wasi_filedelta_t offset, __wasi_whence_t whence, __wasi_filesize_t *retptr0) {
    (void)fd;
    (void)offset;
    (void)whence;
    (void)retptr0;
    return __WASI_ERRNO_NOTSUP;
}

__wasi_errno_t __wasi_fd_sync(__wasi_fd_t fd) {
    (void)fd;
    return __WASI_ERRNO_NOTSUP;
}

__wasi_errno_t __wasi_fd_tell(__wasi_fd_t fd, __wasi_filesize_t *retptr0) {
    (void)fd;
    (void)retptr0;
    return __WASI_ERRNO_NOTSUP;
}

__wasi_errno_t __wasi_fd_write(__wasi_fd_t fd, const __wasi_ciovec_t *iovs, size_t iovs_len, __wasi_size_t *retptr0) {
    (void)fd;
    (void)iovs;
    (void)iovs_len;
    (void)retptr0;
    return __WASI_ERRNO_NOTSUP;
}

__wasi_errno_t __wasi_path_create_directory(__wasi_fd_t fd, const char *path) {
    (void)fd;
    (void)path;
    return __WASI_ERRNO_NOTSUP;
}

__wasi_errno_t __wasi_path_filestat_get(__wasi_fd_t fd, __wasi_lookupflags_t flags, const char *path, __wasi_filestat_t *retptr0) {
    (void)fd;
    (void)flags;
    (void)path;
    (void)retptr0;
    return __WASI_ERRNO_NOTSUP;
}

__wasi_errno_t __wasi_path_filestat_set_times(__wasi_fd_t fd, __wasi_lookupflags_t flags, const char *path, __wasi_timestamp_t atim, __wasi_timestamp_t mtim, __wasi_fstflags_t fst_flags) {
    (void)fd;
    (void)flags;
    (void)path;
    (void)atim;
    (void)mtim;
    (void)fst_flags;
    return __WASI_ERRNO_NOTSUP;
}

__wasi_errno_t __wasi_path_link(__wasi_fd_t old_fd, __wasi_lookupflags_t old_flags, const char *old_path, __wasi_fd_t new_fd, const char *new_path) {
    (void)old_fd;
    (void)old_flags;
    (void)old_path;
    (void)new_fd;
    (void)new_path;
    return __WASI_ERRNO_NOTSUP;
}

__wasi_errno_t __wasi_path_open(__wasi_fd_t fd, __wasi_lookupflags_t dirflags, const char *path, __wasi_oflags_t oflags, __wasi_rights_t fs_rights_base, __wasi_rights_t fs_rights_inheriting, __wasi_fdflags_t fdflags, __wasi_fd_t *retptr0) {
    (void)fd;
    (void)dirflags;
    (void)path;
    (void)oflags;
    (void)fs_rights_base;
    (void)fs_rights_inheriting;
    (void)fdflags;
    (void)retptr0;
    return __WASI_ERRNO_NOTSUP;
}

__wasi_errno_t __wasi_path_readlink(__wasi_fd_t fd, const char *path, uint8_t * buf, __wasi_size_t buf_len, __wasi_size_t *retptr0) {
    (void)fd;
    (void)path;
    (void)buf;
    (void)buf_len;
    (void)retptr0;
    return __WASI_ERRNO_NOTSUP;
}

__wasi_errno_t __wasi_path_remove_directory(__wasi_fd_t fd, const char *path) {
    (void)fd;
    (void)path;
    return __WASI_ERRNO_NOTSUP;
}

__wasi_errno_t __wasi_path_rename(__wasi_fd_t fd, const char *old_path, __wasi_fd_t new_fd, const char *new_path) {
    (void)fd;
    (void)old_path;
    (void)new_fd;
    (void)new_path;
    return __WASI_ERRNO_NOTSUP;
}

__wasi_errno_t __wasi_path_symlink(const char *old_path, __wasi_fd_t fd, const char *new_path) {
    (void)old_path;
    (void)fd;
    (void)new_path;
    return __WASI_ERRNO_NOTSUP;
}

__wasi_errno_t __wasi_path_unlink_file(__wasi_fd_t fd, const char *path) {
    (void)fd;
    (void)path;
    return __WASI_ERRNO_NOTSUP;
}

__wasi_errno_t __wasi_poll_oneoff(const __wasi_subscription_t * in, __wasi_event_t * out, __wasi_size_t nsubscriptions, __wasi_size_t *retptr0) {
    (void)in;
    (void)out;
    (void)nsubscriptions;
    (void)retptr0;
    return __WASI_ERRNO_NOTSUP;
}

__wasi_errno_t __wasi_sock_accept(__wasi_fd_t fd, __wasi_fdflags_t flags, __wasi_fd_t *retptr0) {
    (void)fd;
    (void)flags;
    (void)retptr0;
    return __WASI_ERRNO_NOTSUP;
}

__wasi_errno_t __wasi_sock_recv(__wasi_fd_t fd, const __wasi_iovec_t *ri_data, size_t ri_data_len, __wasi_riflags_t ri_flags, __wasi_size_t *retptr0, __wasi_roflags_t *retptr1) {
    (void)fd;
    (void)ri_data;
    (void)ri_data_len;
    (void)ri_flags;
    (void)retptr0;
    (void)retptr1;
    return __WASI_ERRNO_NOTSUP;
}

__wasi_errno_t __wasi_sock_send(__wasi_fd_t fd, const __wasi_ciovec_t *si_data, size_t si_data_len, __wasi_siflags_t si_flags, __wasi_size_t *retptr0) {
    (void)fd;
    (void)si_data;
    (void)si_data_len;
    (void)si_flags;
    (void)retptr0;
    return __WASI_ERRNO_NOTSUP;
}

__wasi_errno_t __wasi_sock_shutdown(__wasi_fd_t fd, __wasi_sdflags_t how) {
    (void)fd;
    (void)how;
    return __WASI_ERRNO_NOTSUP;
}
