#!/usr/bin/env python3
"""Regenerate mgba-sys/wasi-stubs.c from a wasi-sdk's wasi/api.h.

Usage: gen-wasi-stubs.py $WASI_SDK_PATH > mgba-sys/wasi-stubs.c

Emits a NOTSUP definition for every syscall thunk in wasi-libc's
__wasilibc_real.o EXCEPT the behavior-bearing ones shim.c implements
(environ_get, environ_sizes_get, fd_prestat_get, random_get,
sched_yield, proc_exit). Defining the complete set keeps that archive
member — and with it every wasi_snapshot_preview1 import — out of the
wasm32-unknown-unknown link.
"""
import re, sys

api = open(sys.argv[1] + '/share/wasi-sysroot/include/wasm32-wasip1/wasi/api.h').read()
api = re.sub(r'/\*.*?\*/', '', api, flags=re.S)
IN_SHIM = {'environ_get', 'environ_sizes_get', 'fd_prestat_get', 'random_get', 'sched_yield', 'proc_exit'}
print('// GENERATED by tools/gen-wasi-stubs.py — see that script for why.')
print('#include <wasi/api.h>')
for m in re.finditer(r'__wasi_errno_t (__wasi_(\w+))\((.*?)\)\s*__attribute__', api, flags=re.S):
    full, name, params = m.group(1), m.group(2), ' '.join(m.group(3).split())
    if name in IN_SHIM or name.startswith(('sock_',)) and False:
        continue
    if name in IN_SHIM:
        continue
    args = [re.sub(r'\[\d*\]$', '', p.strip().split()[-1].lstrip('*')) for p in params.split(',')]
    body = ''.join(f'    (void){a};\n' for a in args)
    print(f'\n__wasi_errno_t {full}({params}) {{\n{body}    return __WASI_ERRNO_NOTSUP;\n}}')
